language: python
sudo: required
# command to install dependencies-P /c/Python36 /c/Python36/
  - python -V
install:
  #- ./python-3.6.4.exe InstallAllUsers=1 PrependPath=1
  
  - python -m pip install --upgrade pip
  - pip install --upgrade pip
  - export TZ='Asia/Shanghai'
  - git config --global user.name tobctobc
  - git config --global user.email tobctobc@protonmail.com
  - pip install requests
# command to run tests
script:
  - rm -r -f .git
  - python 1.py
  - cp -f 1.txt ./1/1.txt
  - git init
  - dir
  - git add -A
  - git commit -m "更新`date +"% Y-% m-% d % H:% M"`Travis CI Auto Builder "
  - git push -f "https://tobctobc:${TOKEN}@github.com/tobctobc/plqa.git" master:2

branches:
  only:
    - master
