language: shell
os: windows
sudo: required
# command to install dependencies-P /c/Python36 /c/Python36/
before_install:
  - rm -r -f /c/Python27
  - powershell -Command "Set-ExecutionPolicy RemoteSigned -scope CurrentUser"
  - powershell -Command "Invoke-Expression (New-Object System.Net.WebClient).DownloadString('https://get.scoop.sh')"
  - scoop help
  - scoop install python -a x86
  - python -V
  #- wget -O python-3.6.4.exe -nv https://www.python.org/ftp/python/3.6.4/python-3.6.4.exe 

env: PATH=/c/Users/travis/scoop/apps/python/current:/c/Users/travis/scoop/apps/python/current/Scripts:/c/Users/travis/scoop/apps/python/current/Tools/Scripts:/c/Users/travis/scoop/shims:/c/Users/travis/scoop:$PATH
install:
  #- ./python-3.6.4.exe InstallAllUsers=1 PrependPath=1
  
  - python -m pip install --upgrade pip
  - pip install --upgrade pip
  - export TZ='Asia/Shanghai'
  - git config --global user.name tobctobc
  - git config --global user.email tobctobc@protonmail.com
  - pip install requests
# command to run tests

script:
  - python 1.py
  - dir
  - git add -A
  - git commit -m "更新`date +"% Y-% m-% d % H:% M"`Travis CI Auto Builder "
  - git push -f "https://tobctobc:${TOKEN}@github.com/tobctobc/plqa.git" master:dev
  
deploy:
  # 部署到GitHub Release。
  # 除此之外，Travis CI还支持发布到fir.im、AWS、Google App Engine等
  provider: releases
  # Github oauth token
  api_key: ${TOKEN}
  # 部署文件路径；对于Android就部署生成的 apk 文件
  file: ./1.mp4
  # 避免 Travis CI在部署之前清空生成的APK文件
  skip_cleanup: true
  #on:
    #all_branches: true
branches:
  only:
    - master
